"""Add year

Revision ID: 6475aefa137a
Revises: 4f96a681ff79
Create Date: 2023-04-19 08:55:19.346658

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # NEW


# revision identifiers, used by Alembic.
revision = '6475aefa137a'
down_revision = '4f96a681ff79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_song_year'), 'song', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_year'), table_name='song')
    op.drop_column('song', 'year')
    # ### end Alembic commands ###


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('song', sa.Column('year', sa.Integer(), nullable=True))
#     op.alter_column('song', 'id',
#                existing_type=sa.INTEGER(),
#                nullable=True,
#                autoincrement=True)
#     op.create_index(op.f('ix_song_year'), 'song', ['year'], unique=False)
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_index(op.f('ix_song_year'), table_name='song')
#     op.alter_column('song', 'id',
#                existing_type=sa.INTEGER(),
#                nullable=False,
#                autoincrement=True)
#     op.drop_column('song', 'year')
#     # ### end Alembic commands ###
